### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by jrgnicho**
Changes made during integration.  
CI is broken at the moment due to the new dependencies introduced. @mpowelson can we update the docker?
@marrts any tweaks or code clean up you may want to do prior to merging?

### CODE REVIEW

**Comment by marrts** [comment]
This all looks good to me, the only thing is the CI issue mentioned in #70 and we need to run clang formatting on it, other than that the system seems to be working as expected

**Comment by jrgnicho** [comment]
@mpowelson would you know why this is failing?

**Comment by mpowelson** [comment]
It's odd that it doesn't have a log printout. It looks like it hit the 50 minute time limit, but that might be because something else went wrong. I'd probably wait a bit and restart it, and see if it is a resource thing somehow unless you think some change that was made broke it.

**Comment by jrgnicho** [comment]
@mpowelson I don't know of any change that would've caused this, I removed the realsense dependency from the rosinstall so that shouldn't be an issue anymore

**Pull request merged**
