### PR TITLE
Surface motion time parameterization

### PR DESCRIPTION
**Pull request by marrts**
Implemented a basic differentiation on the joint trajectories to populate the velocity and acceleration fields.

Includes changes in #35

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Would [hungpham2511/toppra](https://github.com/hungpham2511/toppra) perhaps be an option instead? `dx/dt` results in some pretty ugly velocity and acceleration values.

**Comment by mpowelson** [comment]
@gavanderhoorn Are you saying we should write a ROS wrapper for that? It looks like its just Python. Have you had good results from that as opposed to something like https://github.com/schornakj/iterative_spline_parameterization

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn Are you saying we should write a ROS wrapper for that? 

Well, you could also see whether you could reuse [larics/topp_ros](https://github.com/larics/topp_ros).

> Have you had good results from that as opposed to something like https://github.com/schornakj/iterative_spline_parameterization

That would seem to be the MoveIt ISP written by Ken Anderson. It's nice, but I believe `topp-ra` is nicer (and also natively supports Cartesian velocity constraints and other optimisation criteria and costs).

I haven't used [larics/topp_ros](https://github.com/larics/topp_ros) though. So there may be some missing pieces in the ROS wrapper. Probably still worth it to extend/update that instead of writing a new wrapper.

**Comment by gavanderhoorn** [comment]
And of course: whether you will actually notice any improvement in quality of motion greatly depends on what sort of interface you have to the robot that's executing the trajectory.

If it all gets post-processed into mfg proprietary programs, then that translation is most likely so lossy none of this will really matter. It's still nice to have smooth trajectories though.

**Pull request closed without merging**
