### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by mpowelson**
Some changes I found when building on eloquent.

### CODE REVIEW

**Comment by jrgnicho** [comment]
@mpowelson the last commit says `MIght be working ?` so I'm not quite sure that this is ready for review, are you still working on this?

**Comment by jrgnicho** [comment]
It'd be nice if you could squash some of the wip commits

**Comment by mpowelson** [comment]
@jrgnicho Sorry. I forgot this was open as a PR. Let me push these to a different branch.

**Comment by mpowelson** [comment]
These 2 small commits are ready for review

**Review by jrgnicho — APPROVED** [review]

**Comment by jrgnicho** [comment]
@mpowelson thanks

**Pull request merged**
