### PR TITLE
Integrate perception configuration

### PR DESCRIPTION
**Pull request by jrgnicho**
This PR Integrates the scanning and registration changes in #39 to the rest of the application.  At the moment the get_configuration service advertised by the gui times out so it still a WIP

### CODE REVIEW

**Comment by mpowelson** [comment]
What is the status of this? This seems like a pretty massive PR that touches about everything. Trying to develop off master seems like a bad idea if this is going to get merged. Is it in at least a workable state such that we could get this merged in?

**Comment by mpowelson** [comment]
@jrgnicho @marrts any update?

**Comment by marrts** [comment]
I don't know anything about the progress of this PR, but I agree that it would be nice to have this to work off of.

**Comment by jrgnicho** [comment]
I'll wrap it up today or tomorrow, sorry for the delay

**Comment by jrgnicho** [comment]
This is ready for review
It currently loads the configuration file and setups up all of the manager.   Motion planning during scanning fails at the moment but it may be that the scan poses passed to it are unreachable.  I'll be fixing this in subsequent PR's

**Comment by mpowelson** [comment]
I did not see anything blatantly obvious. I would be inclined to just merge in and fix anything we find broken in future PRs. 

CI is failing because clang format needs to be run and the iterative spline needs to be added to the rosdep skip keys. I submitted a PR against your branch that hopefully will fix it. @jrgnicho

**Comment by jrgnicho** [comment]
@mpowelson thanks for reviewing, I already merged your PR

**Pull request merged**
