### PR TITLE
Visualization improvements

### PR DESCRIPTION
**Pull request by jrgnicho**
Hides selectable regions when the part rework state is exited

### CODE REVIEW

**Comment by jrgnicho** [comment]
The latest in the region detection repository is needed for this change to work

**Comment by jrgnicho** [comment]
@marrts ping

**Comment by marrts** [comment]
I'll look at this right now, sorry for the delay

**Review by marrts — APPROVED** [review]
Looks great to me. Also the motion planning worked just fine from the given initial pose, not sure why your system was having issues with that

**Comment by jrgnicho** [comment]
> Looks great to me. Also the motion planning worked just fine from the given initial pose, not sure why your system was having issues with that

OK, thanks for reviewing

**Pull request merged**
