### PR TITLE
Added region detection source dependency

### PR DESCRIPTION
**Pull request by jrgnicho**
As Per Title

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@jrgnicho It is odd that there is nothing in the log. Have you tried restarting it and the issue persists?

**Comment by jrgnicho** [comment]
@Levi-Armstrong all I can think of is that it is timing out as the total build time reaches the ~50 minute threshold

**Comment by Levi-Armstrong** [comment]
Yea I think it is also timing out. I noticed that you are building tesseract_ext from source. I recommend updating your docker to already have these installed. I am doing this for the tesseract ci. You can find the docker file in the docker repository which should cut your ci time way down.

**Comment by jrgnicho** [comment]
@Levi-Armstrong ok, I'll give that a try

**Pull request merged**
