### PR TITLE
Wsu integration 6 11

### PR DESCRIPTION
**Pull request by marrts**
Here are the all the changes I have made while at WSU, the system seems to run pretty well with all of these settings.

### CODE REVIEW

**Comment by jrgnicho** [comment]
I get the following error from the motion planning server when I run it, it errors out immediately
```
Warning: No version number was provided so latest parser will be used.
         at line 86 in /home/jnicho/ros2/eloquent/crs_ws/src/tesseract/tesseract/tesseract_scene_graph/src/srdf_model.cpp
[INFO] [crs.motion_planning_server]: Part successfully added to tesseract environment
GOT REQUEST
SET TARGET LINK
SET N STEPS
INITIALIZED CLASS
DEFINED START
[ERROR] [crs.motion_planning_server]: FAILED TO FIND A FEASIBLE SOLUTION
[ERROR] [crs.motion_planning_server]: 
```

**Comment by marrts** [comment]
This means that the attempted end point of the freespace plane is not reachable, likely it is a point that is in collision or out of reach of the robot.

**Comment by jrgnicho** [comment]
I think it's because the robot based moved, maybe I just have to delete my config files so that new ones are recreated from the default one?

**Comment by marrts** [comment]
Is there anything preventing this from being merged in at the moment?

**Comment by jrgnicho** [comment]
This works with the most recent data files

**Pull request merged**
