### PR TITLE
Feature/collision pairs planning

### PR DESCRIPTION
**Pull request by marrts**
Added collision pairs so that plans can be made on the surface of the part

Added tesseract env part loading to the process so that the planner respects its collision geometry.

### CODE REVIEW

**Comment by jrgnicho** [comment]
It looks like it fail because the docker doesn't have the realsense library installed

**Comment by marrts** [comment]
Yeah, I added it because we’ll need it for the real system, but it needs an sdk installed to build so I’m not sure the best way to make sure it succeeds in CI.

**Comment by jrgnicho** [comment]
We'll just have to update the docker to have the needed system dependency, for now I'll build and run locally and merge if it all works

**Comment by jrgnicho** [comment]
@marrts  I have conflicting realsense installation instructions, which ones did you follow? I've found [these](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md)

**Comment by jrgnicho** [comment]
I could't get a successful build, there's a tesseract dependency mismatch
```
fatal error: tesseract_scene_graph/parser/srdf_parser.h: No such file or directory
 #include <tesseract_scene_graph/parser/srdf_parser.h>
```

**Comment by marrts** [comment]
Changed the git hash of tesseract_ros2. This should fix the problem.

**Comment by jrgnicho** [comment]
OK i'll try it out

**Comment by jrgnicho** [comment]
I got it to build but the motion planning server node crashes. When I do a backtrace with gdb it appears that the error comes from the libjsoncpp library, does that need to be built from source?

**Comment by marrts** [comment]
I have it built from source on my system, but that is dependent on the computer. Not sure what the determining factor is but some systems seem to require it built from source and others don't. Something to do with linking against tesseract which uses it.

Once you pull down the source code you have to comment out the following sections:
in include/json/value.h
```
#if JSON_USE_NULLREF
   // Binary compatibility kludges, do not use.
   static const Value& null;
   static const Value& nullRef;
#endif
```

and in src/lib_json/json_value.cpp:
```
#if JSON_USE_NULLREF
...
#endif
```

then run the following from the main directory:
```
mkdir -p build/debug
cd build/debug
cmake -DCMAKE_BUILD_TYPE=release -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_INCLUDEDIR=include/jsoncpp -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles" ../..
make
sudo make install
```

**Comment by mpowelson** [comment]
@marrts Are these steps documented in some Tesseract issue? Obviously we need to try to fix the underlying issue (though it may go away in Ubuntu 20), but it would be good to put this somewhere visible.

**Comment by marrts** [comment]
No, these worked for me and I had them saved from an email when I relayed them to someone else and it also worked for them.

**Comment by jrgnicho** [comment]
@marrts ok I'll give this a try

**Comment by jrgnicho** [comment]
@marrts thanks for the contribution

**Pull request merged**
