### PR TITLE
Integrate crs data package

### PR DESCRIPTION
**Pull request by jrgnicho**
This PR adds the crs_process_data package which contains the part meshes and toolpaths for the main and surrogate workcells

### CODE REVIEW

**Review by marrts — COMMENTED** [review]
All looks good to me, I am just confused as to what the surrogate1 directory represents in the new crs_process_data package

**Comment by jrgnicho** [comment]
> All looks good to me, I am just confused as to what the surrogate1 directory represents in the new crs_process_data package

It's the swri cell I just went for a more generic name

**Comment by marrts** [comment]
Okay, sounds good to me

**Comment by jrgnicho** [comment]
This has been superseded by PR #77

**Pull request closed without merging**
