### PR TITLE
Variable minimum raster length

### PR DESCRIPTION
**Pull request by marrts**
Added field in PlanProcessMotions.srv that will make minimum raster length 0 if set to true

Added check in motion planning server for this field

Needs to be incorporated to the main applications

This is committed on top of PR #100

### CODE REVIEW

**Comment by marrts** [comment]
@jrgnicho Do you think you could implement the application side of this improvement?

**Comment by jrgnicho** [comment]
Is this still WIP?

**Comment by marrts** [comment]
It should be working, just the application side of things hasn't been implemented, also I'll need to rebase on integration now that you merged in #100

**Comment by jrgnicho** [comment]
Should I holdoff then?

**Comment by marrts** [comment]
Either you can checkout this branch and make the changes to the application or you can merge it in and then make the changes on integration. I don't have a preference either way.

**Comment by marrts** [comment]
Closing because we decided not to pursue this approach further

**Pull request closed without merging**
