### PR TITLE
Add GUI and initial area selection code

### PR DESCRIPTION
**Pull request by mpowelson**
Area selection currently only draws on the part. It does not actually crop anything. More importantly it also adds a preliminary gui which can be used to load a mesh into rviz and move around the state machine.

There is a bit of setup in the readme. Here's a screenshot of the gui.

Screenshot from 2020-02-04 16-32-56

### CODE REVIEW

**Comment by mpowelson** [comment]
@marrts Do you want to pull this down and test it? I created an integration branch so we can get some of these changes merged into one place without a formal review. Then we can review them more carefully in a few weeks to get them merged into master.

**Comment by mpowelson** [comment]
@marrts I set up CI on this repo, so we shouldn't have to pull down code to make sure it doesn't break builds. Do you want to take a look at this or should I just merge it into integration when CI passes?

**Comment by marrts** [comment]
The GUI seems to be working well for me

**Comment by mpowelson** [comment]
I rebased this onto Jorge's changes. Now I'll wait to make sure CI still passes.

**Comment by mpowelson** [comment]
Just to record what happened, there were some pretty severe rebase issues when I rebased Jorge's branch onto the CI branch. Long story short, we just decided to do it the other way and made Jorge's scan aquisition branch integration and then merged CI and the GUI into that - making this PR irrelevant.

**Pull request closed without merging**
