### PR TITLE
Fix/tesseract update 3 5 2020

### PR DESCRIPTION
**Pull request by marrts**
Changes on top of #40 that allow motion planning to work with tesseract and trajopt update as of March 5th

### CODE REVIEW

**Comment by mpowelson** [comment]
We'll need to rebase the CI branch of tesseract (with the ignores) onto these branches for this to work. However, if we update to the latest changes we should be able to get rid of the colcon ignores in Tesseract as those packages are gone.

Do you want to do that or do you want me to? bf73e8ff1b0d51e62ab6f1b2df1f6d14d1e44f8d is really the last one you need. You might just be able to change the rosinstall. The changes b/n what you have here and there are pretty minimal.

**Comment by marrts** [comment]
Seems like the only change should be the rosinstall, I made that change, but if for some reason this fails I will investigate it further and fix any other necessary changes.

**Comment by marrts** [comment]
It failed for the following reason: 
`tesseract_monitoring: Cannot locate rosdep definition for [orocos-kdl]`
This seems like an issue with tesseract on bf73e8f

**Comment by mpowelson** [comment]
Try now. It was an issue in Tesseract_ros2 (https://github.com/ros-industrial-consortium/tesseract_ros2/pull/13)

**Comment by marrts** [comment]
Update rosinstall to point to newest tesseract_ros2 commit?

**Comment by mpowelson** [comment]
Ok. Well it looks like Tesseract_ros depends on the latest changes in Tesseract which I suppose is not surprising. Maybe the easiest thing is just to add orocos-kdl to the rosdep skip keys as well.

**Comment by marrts** [comment]
Looks like I didn't actually update my motion planner to the newest tesseract changes properly, I will get around to fixing this later today or tomorrow.

**Comment by marrts** [comment]
It successfully built on fd30037 but it didn't have clang formatting. I fixed that and it should be good to go now.

**Review by mpowelson — APPROVED** [review]
Just in general we need to review how we handle multiple environments in projects like this. But that is a discussion for another day.

**Comment by mpowelson** [comment]
@marrts @jrgnicho Any reason not to merge?

**Comment by marrts** [comment]
I see none, just need to make sure everyone updates tesseract, tesseract_ros2, and trajopt.

**Pull request merged**
